
#ifdef _HAVE_CONFIG_H
#include <config.h>
#endif

#include "parser.h"

#include <dtq-bison.h>
#include <stdlib.h>
#include <stdbool.h>
#include <assert.h>
#include <stdio.h>
#include <string.h>

/* flex and bison stuff */

typedef struct yy_buffer_state * YY_BUFFER_STATE;
extern int yyparse();
extern YY_BUFFER_STATE yy_scan_string(const char * str);
extern void yy_delete_buffer(YY_BUFFER_STATE buffer);

/** Parse a node test from a string
 * \param expr node test expression
 * \return AST of the expression on success, NULL otherwise.
 * \note In case of an error (e.g. syntax error), the error is printed to
 *  stderr.
 */
struct NodeTest * parseNodeTestExpr(const char * expr)
{
	struct NodeTest * parsedExpression;

	/* tell the lexer to scan the given expression string */
	YY_BUFFER_STATE buffer = yy_scan_string(expr);
	/* let the parser do its magic */
	int ret = yyparse(&parsedExpression, expr);
	/* free resources */
	yy_delete_buffer(buffer);

	if (ret) {
		/* parsing failed */
		return NULL;
	} else {
		/* success */
		return parsedExpression;
	}
}

/** Callback for lexer error
 * \param yytext unknown character (only [0] is filled by now)
 */
void lexError(const char * yytext)
{
	fprintf(stderr, "Lex Error: %s\n", yytext);
}

/** Callback for parser error
 * \param parsedExpression unneeded
 * \param expr unparsed expression (=expr of praseNodeTest())
 * \param s error string, generated by bison
 */
void yyerror(struct NodeTest ** parsedExpression, const char * expr,
	const char * s)
{
	/* we want to print something like that:
	 *
	 * Syntax error at some/expression/errorHERE/unparsed
	 *                                 ^^^^^^^^^
	 *
	 * i.e. we want to underline the part of the expression containing the
	 *  error. If the expression is too long, we shorten it on the left
	 *  and maybe right side.
	 */

	const char * err = expr;
	size_t errlen = yylloc.last_column - yylloc.first_column + 1;

	/* this is where the erroneous substring begins */
	size_t offset = yylloc.first_column - 1;
	size_t printLen = strlen(expr);
	bool truncate_l = false;
	bool truncate_r = false;
	if (printLen > 60) {
		/* truncate only if the complete expression exceeds 60 characters */
		if (offset >= 10) {
			/* truncate on the left if there are more than 10 characters:
			 * -> limit it to 5
			 */
			err += offset - 5;
			printLen -= offset - 5;
			offset = 5;
			truncate_l = true;
		}
		if (printLen - errlen >= 10) {
			/* truncate on the right if there are more than 10 characters:
			 * -> limit to 5
			 */
			printLen = errlen + 5;
			truncate_r = true;
		}
	}

	/* print generated message of the parser */
	offset += printf("%s at ", s);
	if (truncate_l) {
		/* if truncated on the left : print indicator */
		offset += 1;
		printf("…");
	}
	/* print the expression (i.e. it's erroneous substring) */
	printf("%.*s", (int)printLen, err);
	if (truncate_r) /* if truncated on the right: print indicator */
		printf("…");
	printf("\n");

	/* print spaces until we reach the erroneous substring */
	const char spc[10] = { [0 ... 9] = ' ' };
	for (; offset >= 10; offset -= 10)
		fwrite(spc, sizeof *spc, sizeof spc, stdout);
	if (offset)
		fwrite(spc, sizeof *spc, offset, stdout);

	/* print circumflexes below the erroneous substring */
	const char mark[10] = { [0 ... 9] = '^' };
	for (; errlen >= 10; errlen -= 10)
		fwrite(mark, sizeof *mark, sizeof mark, stdout);
	if (errlen)
		fwrite(mark, sizeof *mark, errlen, stdout);
	puts("");
}

/** Instantiate a new node test.
 * \param type node test type
 * \param name optional node name, ownership is transferred
 * \param properties optional properties test, ownership is transferred
 * \param subExpr optional sub expression, ownership is transferred
 * \param node test
 */
struct NodeTest * newNodeTest(enum NODE_TEST_TYPE type, char * name,
	struct PropertyTest * properties, struct NodeTest * subExpr)
{
	struct NodeTest * expr = malloc(sizeof *expr);
	assert(expr);
	expr->type = type;
	expr->name = name;
	expr->properties = properties;
	expr->subExpr = subExpr;
	return expr;
}

/** Instantiate a new atomic property existence test
 * \param property property name
 * \return property test
 */
struct AtomicPropertyTest * newAtomicPropertyTestExist(char * property)
{
	struct AtomicPropertyTest * expr = malloc(sizeof *expr);
	assert(expr);
	expr->type = ATOMIC_PROPERTY_TEST_TYPE_EXIST;
	expr->property = property;
	return expr;
}

/** Instantiate a new atomic property integer test
 * \param op comparison operator
 * \param property property name
 * \param integer integer to test against
 * \return property test
 */
struct AtomicPropertyTest * newAtomicPropertyTestInteger(
	enum ATOMIC_PROPERTY_TEST_OP op, char * property, int integer)
{
	struct AtomicPropertyTest * expr = malloc(sizeof *expr);
	assert(expr);
	expr->type = ATOMIC_PROPERTY_TEST_TYPE_INT;
	expr->op = op;
	expr->property = property;
	expr->integer = integer;
	return expr;
}

/** Instantiate a new atomic property string test
 * \param op comparison operator
 * \param property property name
 * \param string string to test against, ownership is transferred
 * \return property test
 */
struct AtomicPropertyTest * newAtomicPropertyTestString(
	enum ATOMIC_PROPERTY_TEST_OP op, char * property, char * string)
{
	struct AtomicPropertyTest * expr = malloc(sizeof *expr);
	assert(expr);
	expr->type = ATOMIC_PROPERTY_TEST_TYPE_STR;
	expr->op = op;
	expr->property = property;
	expr->string = string;
	return expr;
}

/** Free an atomic property test.
 * \param test atomic property test to be freed. May be NULL
 */
void freeAtomicPropertyTest(struct AtomicPropertyTest * test)
{
	if (!test)
		return;

	/* free also data if necessary */
	if (test->type == ATOMIC_PROPERTY_TEST_TYPE_STR)
		free(test->string);
	free(test->property);
	free(test);
}

/** Free a property test.
 * \param test property test to be freed. May be NULL
 */
void freePropertyTest(struct PropertyTest * test)
{
	if (!test)
		return;

	/* free all child properties */
	switch (test->type) {
	case PROPERTY_TEST_OP_AND:
	case PROPERTY_TEST_OP_OR: {
		struct PropertyTest * subTestLeft = test->left;
		struct PropertyTest * subTestRight = test->right;
		free(test);
		/* allow tail recursion, although it's most likely that only the right
		 * child will benefit from that.
		 */
		freePropertyTest(subTestLeft);
		freePropertyTest(subTestRight);
		break;
	}
	case PROPERTY_TEST_OP_NEG: {
		struct PropertyTest * subTest = test->neg;
		free(test);
		/* allow tail recursion */
		freePropertyTest(subTest);
	}
		break;
	case PROPERTY_TEST_OP_TEST: {
		struct AtomicPropertyTest * subTest = test->test;
		free(subTest);
		/* allow tail recursion */
		freeAtomicPropertyTest(subTest);
	}
		break;
	}
}

/** Free a node test.
 * \param test node test to be freed. May be NULL
 */
void freeNodeTest(struct NodeTest * test)
{
	if (!test)
		return;

	free(test->name);
	freePropertyTest(test->properties);
	struct NodeTest * next = test->subExpr;
	free(test);
	/* allow tail recursion */
	freeNodeTest(next);
}

/** Readable operator names */
static const char * testOperators[] = {
	[ATOMIC_PROPERTY_TEST_OP_EQ] = "=",
	[ATOMIC_PROPERTY_TEST_OP_NE] = "!=",
	[ATOMIC_PROPERTY_TEST_OP_LE] = "<=",
	[ATOMIC_PROPERTY_TEST_OP_GE] = ">=",
	[ATOMIC_PROPERTY_TEST_OP_LT] = "<",
	[ATOMIC_PROPERTY_TEST_OP_GT] = ">",
	[ATOMIC_PROPERTY_TEST_OP_CONTAINS] = "~="
};

/** Dump an atomic property test to stdout.
 * \param test property test to be printed
 */
static void printAtomicPropertyTest(const struct AtomicPropertyTest * test)
{
	const char * op = testOperators[test->op];
	switch (test->type) {
	case ATOMIC_PROPERTY_TEST_TYPE_EXIST:
		printf("%s", test->property);
		break;
	case ATOMIC_PROPERTY_TEST_TYPE_INT:
		printf("%s %s 0x%x", test->property, op, test->integer);
		break;
	case ATOMIC_PROPERTY_TEST_TYPE_STR:
		printf("%s %s \"%s\"", test->property, op, test->string);
		break;
	default:
		assert(false);
	}
}

/** Dump a property test to stdout.
 * \param test property test to be printed
 */
static void printPropertyTest(const struct PropertyTest * test)
{
	switch (test->type) {
	case PROPERTY_TEST_OP_AND:
		printf("(");
		printPropertyTest(test->left);
		printf(" & ");
		printPropertyTest(test->right);
		printf(")");
		break;
	case PROPERTY_TEST_OP_OR:
		printf("(");
		printPropertyTest(test->left);
		printf(" | ");
		printPropertyTest(test->right);
		printf(")");
		break;
	case PROPERTY_TEST_OP_NEG:
		printf("!(");
		printPropertyTest(test->neg);
		printf(")");
		break;
	case PROPERTY_TEST_OP_TEST:
		printAtomicPropertyTest(test->test);
		break;
	}
}

/** Dump a node test to stdout.
 * \param test node test to be printed
 */
void printNodeTest(const struct NodeTest * test)
{
	if (test->type != NODE_TEST_TYPE_ROOT)
		printf("/");

	if (test->type == NODE_TEST_TYPE_NODE && test->name)
		printf("%s", test->name);

	if (test->properties) {
		printf("[");
		printPropertyTest(test->properties);
		printf("]");
	}

	if (test->subExpr)
		printNodeTest(test->subExpr);
}
